### ISSUE TITLE
MathJax bug

### ISSUE THREAD

**Issue by sandersantema** [hgiesel/closet#34]
**Describe the bug**
Other than the generated mathjax formula itself a piece of light gray text is shown. As can be seen here:
![image](https://user-images.githubusercontent.com/21057514/97811015-1a6df880-1c78-11eb-8e5a-ddcfb50a9a75.png)

Code used for note:
```
\(x^2\) [[c1::hallo]]
```
However after one review this grey text disappears:
![image](https://user-images.githubusercontent.com/21057514/97811168-15f60f80-1c79-11eb-84a7-3e113e2f6d0e.png)

The gray text only reappears when stopping the reviewer i.e. exiting to the browse window.
 
More weird stuff happens when I include a mathjax formula in the cloze:
![image](https://user-images.githubusercontent.com/21057514/97811380-8c474180-1c7a-11eb-863a-7e3ae15422bf.png)

Code used for note:
```
\(x^2\) [[c1::\(x^1\) hallo]]
[[c2::\(test\)]]
[[c3::\[test\] ]]
```
 - Anki client: Anki Desktop, version 2.1.35 (From th
 official releases), Linux openSUSE Tumbleweed

**Debug information**

#### Method 1
`initCloset()` fails, this doesn't make a whole load of sense though given that clozes without mathjax are working just fine.
![image](https://user-images.githubusercontent.com/21057514/97811297-f9a6a280-1c79-11eb-9268-d95f10fb9b9b.png)

#### Method 2
(The file has an added `.zip` extension)
[test.apkg.zip](https://github.com/hgiesel/closet/files/5471540/test.apkg.zip)

**Comment by hgiesel** [comment]
The "method 1" description was outdated. It is basically to ensure that you Closet is actually installed on that card type, which is definitely the case here.

I'm working on the MathJax support.

**Comment by hgiesel** [comment]
I just uploaded a new version `v0.2.1`, which supports MathJax. You need to reinsert Closet using Asset Manager again however.

**Comment by hgiesel** [comment]
I had to take back most of the MathJax support I added, because how flimsy MathJax behaves on mobile.
I will postpone the next attempt till after Anki updates to MathJax 3 which supports a more stable Promise API for synchronisation rather than building their own mechanisms. I have opened a [PR for this](https://github.com/ankitects/anki/pull/809).

**Comment by sandersantema** [comment]
Looks really good! If I desperately need mathjax anyways I'll probably just try the previous version out and otherwise I'll wait for more updates :)

**Comment by hgiesel** [comment]
I just updated to v0.2.3 which even works with MathJax of the current Anki version. There were actually some longstanding issues, which I simply never noticed, but are now fixed.

**Comment by sandersantema** [comment]
Fantastic! Thank you for the quick fixes.

**Comment by sandersantema** [comment]
Closet now seems to work with mathjax except for embedding mathjax into a closet cloze which renders the mathjax but doesn't render the cloze itself.

`\(x^2\) [[c1::\(x^1\) hallo]]` will show as:
![image](https://user-images.githubusercontent.com/21057514/99107945-e59e6180-25e6-11eb-86e6-6bdfc23b0454.png)

I'm using the latest anki beta, `2.1.36beta2`. Is this the expected behaviour?

**Comment by hgiesel** [comment]
I cannot recreate this, after the update.
Are you sure you actually updated it. You also need to reinsert Closet using Asset Manager, as some of the code on the template itself changed.

**Comment by sandersantema** [comment]
> Are you sure you actually updated it. You also need to reinsert Closet using Asset Manager, as some of the code on the template itself changed.

I have indeed reinserted Closet, which solved all of the ways in which mathjax wasn't working. But unfortunately it still doesn't seem to be working.

I have a suspicion it might be something about my local setup although I can reproduce this bug using a fresh anki profile and with the closet script inserted into the default basic cards. 

Maybe it has something to do with one of my installed plugins?
![image](https://user-images.githubusercontent.com/21057514/99127892-b0573b00-2609-11eb-8e39-0d8cd4d75311.png)

**Comment by hgiesel** [comment]
You could try and start Anki while holding Shift, which will disable all add-ons temporarily. The template should still work however.

**Comment by sandersantema** [comment]
> You could try and start Anki while holding Shift, which will disable all add-ons temporarily. The template should still work however.

Unfortunately still doesn't work, I'll try some other things and follow up if anything changes.

**Comment by sandersantema** [comment]
It seems like writing the template to a note type doesn't work anymore. Although it did seem to work a little while ago nothing gets written to the note now that I try.

**Comment by hgiesel** [comment]
@sandersantema I have good news, I figured out the issue.
I will push out a fix possibly tomorrow. For now, you can fix the issue (and this may sound crazy...) by making the whole MathJax expression (including `\(` to `\)`) italic or bold.

**Comment by sandersantema** [comment]
> @sandersantema I have good news, I figured out the issue.
> I will push out a fix possibly tomorrow. For now, you can fix the issue (and this may sound crazy...) by making the whole MathJax expression (including `\(` to `\)`) italic or bold.

Very nice! Making the whole expression bold or italic does work, quite an amusing fix :) I look forward to start using closet a lot more, this issue was a blocker but now that it's resolved I can use it.

**Comment by sandersantema** [comment]
I'll close the issue for now, given that making the whole mathjax expression bold or italic works and it should work without if your fixes are merged.

**Comment by hgiesel** [comment]
I've uploaded a new version (v0.2.4) to AnkiWeb, which means you probably don't need to use the "italic"-trick anymore :) 

80eb9c9333c639beda2bf04d37
